language: php

matrix:
  include:
    - php: 7.3
      dist: precise
    - php: 7.4
      dist: trusty
    - php: precise
  allow_failures:
    - php: nightly

env:
  - COMPOSER_ALLOW_XDEBUG=0
  - XDEBUG_MODE=coverage

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer validate

install:
  - composer install

script:
  - composer test:all

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml
